export const TYPES = {
	Application: Symbol.for('Application'),
	ILogger: Symbol.for('ILogger'),
	UserController: Symbol.for('UserController'),
	UserService: Symbol.for('UserService'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	ConfigService: Symbol.for('ConfigService'),
	PrismaService: Symbol.for('PrismaService'),
	UsersRepository: Symbol.for('UsersRepository'),
	PurchasesRepository: Symbol.for('PurchasesRepository'),
	PurchasesService: Symbol.for('PurchasesService'),
	PurchasesController: Symbol.for('PurchasesController'),
	UsersEnkodController: Symbol.for('UsersEnkodController'),
	UsersEnkodService: Symbol.for('UsersEnkodService'),
	UsersEnkodRepository: Symbol.for('UsersEnkodepository'),
	OrdersController: Symbol.for('OrdersController'),
	OrdersService: Symbol.for('OrdersService'),
	OrdersRepository: Symbol.for('OrdersRepository'),
	GoogleSheetService: Symbol.for('GoogleSheetService'),
	SalesControllerService: Symbol.for('SalessControllerService'),
	SalesController: Symbol.for('SalesController'),
};
