export const TYPES = {
	Application: Symbol.for('Application'),
	ILogger: Symbol.for('ILogger'),
	UserController: Symbol.for('UserController'),
	UserService: Symbol.for('UserService'),
	ExceptionFilter: Symbol.for('ExceptionFilter'),
	ConfigService: Symbol.for('ConfigService'),
	PrismaService: Symbol.for('PrismaService'),
	UsersRepository: Symbol.for('UsersRepository'),
	PurchasesRepository: Symbol.for('PurchasesRepository'),
	PurchasesService: Symbol.for('PurchasesService'),
	PurchasesController: Symbol.for('PurchasesController'),
	UsersEnkodController: Symbol.for('UsersEnkodController'),
	UsersEnkodService: Symbol.for('UsersEnkodService'),
	UsersEnkodRepository: Symbol.for('UsersEnkodepository'),
	OrdersRepository: Symbol.for('PurchasesRepository'),
	OrdersService: Symbol.for('PurchasesService'),
	OrdersController: Symbol.for('PurchasesController'),
};
